name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH로 EC2에 접속하기
        #어떤 라이브러리를 사용할건지
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          #sudo fuser -k -n tcp 8080 || true -> 8080포트가 사용중이지 않아도 에러가 발생하지 않게 하기
          # 2>&1 명령어가 실패해도 파일에 넣고 실패해도 파일에 넣는다
          script: |
            cd /home/ubuntu/ToyBoard
            git pull origin main
            ./gradlew clean build
            sudo fuser -k -n tcp 8080 || true 
            nohup java -jar build/libs/*SNAPSHOT.jar > ./output.log 2>&1 &
