name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository에 올린 파일들을 불러오기
        #repository에 올린 코드를 githubaction컴퓨터로 불러오는 라이브러리
        uses: actions/checkout@v4

      - name: TEST
        run: |
          ls
          pwd

      - name: JDK 17버전 설치
        #자바 설치 라이브러리
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      #application.yml파일은 gitignore로 해뒀기 때문에 만들어서 넣어줌 (소스는 이미 가져와 있는건가?)
      - name: application.yml파일 만들기
        run: echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./src/main/resources/application.yml

      - name: 테스트 및 빌드하기 - gradlew 실행권한 주기
        run: chmod +x ./gradlew

      - name: 테스트 및 빌드하기 - gradlew로 빌드하기
        run: ./gradlew clean build

      - name: 빌드된 파일 이름 변경하기
        run: mv ./build/libs/*SNAPSHOT.jar ./project.jar

      - name: SCP로 EC2에 빌드된 파일 전송하기
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{secrets.EC2_HOST}}
          username: ${{secrets.EC2_USERNAME}}
          key: ${{secrets.EC2_PRIVATE_KEY}}
          #대상파일
          source: project.jar
          #전송할 위치
          target: /home/ubuntu/ToyBoard-server/tobe


      - name: SSH로 EC2에 접속하기
        #어떤 라이브러리를 사용할건지
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          #1. 기존 jar파일이 있는 current디렉터리 삭제
          #2. 삭제한 current디렉터리 다시 생성
          #3. scp로 옮긴 jar파일을 current디렉터리로 이동
          #4. 실행되고있는 서버 프로세스 종료
          #5. scp로 옮긴 jar파일을 실행
          #6. tobe디렉터리 삭제
          script: |
            rm -rf /home/ubuntu/ToyBoard-server/current
            mkdir /home/ubuntu/ToyBoard-server/current
            mv /home/ubuntu/ToyBoard-server/tobe/project.jar /home/ubuntu/ToyBoard-server/current/project.jar
            cd /home/ubuntu/ToyBoard-server/current
            sudo fuser -k -n tcp 8080 || true
            nohup java -jar project.jar > ./output.log 2>&1 &
            rm -rf /home/ubuntu/ToyBoard-server/tobe
         
            
